services:
  ldap_server:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ADMIN_PASSWORD: 12345
      LDAP_BASE_DN: dc=chnk,dc=org
      LDAP_DOMAIN: chnk.org
      LDAP_ORGANISATION: "LDAP Inc."
    hostname: ldap.chnk.org
    command: --copy-service
    ports:
      - 389:389
    volumes:
      - ./MQTT.Server/data/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'

  mqtt-server:
    build:
      context: .
      dockerfile: MQTT.Server/Dockerfile
    ports:
      - "707:707"
    networks:
      - mqtt-network
      - default
    container_name: mqtt-server
    depends_on:
      - ldap_server

  mqtt-client:
    build:
      context: .
      dockerfile: MQTT.Client/Dockerfile
    depends_on:
      - mqtt-server
    networks:
      - mqtt-network
    environment:
      - MQTT_SERVER_HOST=mqtt-server
    container_name: mqtt-client

networks:
  mqtt-network:
    driver: bridge 